{
    'name': 'Construction Management',
    'version': '18.0.1.0.0',
    'category': 'Industries',
    'summary': 'A comprehensive module for managing construction projects in Odoo.',
    'author': 'Jules',
    'website': '',
    'license': 'AGPL-3',
    'depends': [
        'project',
        'hr_timesheet',
        'planning',
        'documents',
        'purchase',
        'account',
        'stock',
        'hr',
        'quality_control',
        'maintenance',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/project_views.xml',
        'views/document_management_views.xml',
        'views/budget_and_cost_views.xml',
        'views/procurement_and_inventory_views.xml',
        'views/site_and_field_views.xml',
        'views/workforce_and_timesheet_views.xml',
    ],
    'installable': True,
    'application': True,
}
